services:
  postgres:
    image: postgres:latest
    container_name: postgres_container_post
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: post_pastbin_db
    ports:
      - "5433:5432"